apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: spring-sensors
  description: Spring Sensors 
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors'
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./groups/org.yaml
    - ./resources/database/resource-postgres.yaml
    - ./components/service/component.yaml
    - ./systems/system.yaml
    - ./domains/domain.yaml
